default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quizdata_development

test:
  <<: *default
  database: quizdata_test

production:
  <<: *default
  database: quizdata_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
